### ISSUE TITLE
[Idea] Opinion on Creating a List of Supported ELF Files and Stable Games

### ISSUE THREAD

**Issue by MandaThePanda** [McCaulay/mast1c0re#2]
Hey McCaulay,

I was wondering if you could give me your opinion on something. I'm thinking about creating a list of supported ELF files for homebrew or games that don't crash in the main menu or something similar. Do you think this is a good idea? I'd love to hear your thoughts on it.

Thanks!

**Comment by McCaulay** [comment]
Sure, I am thinking of moving the ps2 game loader project into it's own Git repository given it seems to be the most common sample people want to try out.  Also I am planning on adding support for loading a emulator configuration file so that game's can be tuned to be more compatible.

But feel free to add a game compatibility list.

**Comment by MandaThePanda** [comment]
Thanks for considering my suggestion. Once the PS2 game loader project has been moved into its own Git repository and support for loading an emulator configuration file has been added, I think it would be a great idea to create a game compatibility list in the README.md file and fill it with issues. This could be a really helpful resource for users who are looking for supported ELF files or stable games. Let me know if I can assist you with this in any way.

**Comment by josesilveiraa** [comment]
> Sure, I am thinking of moving the ps2 game loader project into it's own Git repository given it seems to be the most common sample people want to try out. Also I am planning on adding support for loading a emulator configuration file so that game's can be tuned to be more compatible.
> 
> But feel free to add a game compatibility list.

The config idea is a great one. Unfortunately, my ps5 started overheating like 8 days ago and I can't turn it on anymore. I bought a new cooler today, hope it fixes the issue.

**Comment by MandaThePanda** [comment]
I wanted to let you know that I have decided to close the Github issue we were discussing. Once I see everything moved, I will be happy to help with the list of ELF files that work using your fantastic work.

Thank you for your hard work and dedication to this project. I appreciate your help and I look forward to working with you on this.

**Comment by McCaulay** [comment]
@MandaThePanda Thanks I appreciate it. See this repository for the moved PS2 game loader - [mast1c0re-ps2-network-game-loader](https://github.com/McCaulay/mast1c0re-ps2-network-game-loader)
