### ISSUE TITLE
Is Support for PS5 7.01 planned?

### ISSUE THREAD

**Issue by zm1868179** [McCaulay/mast1c0re#6]
is their work being done to locate the PS5 7.01 Offsets.

I wanted to try to play around with this but it seems the offsets for 7.00/7.01 haven't been found yet.

**Comment by McCaulay** [comment]
Direct syscall-only support has been. Cannot add libkernel function support currently as I do not have access to v7.01 decrypted libkernel_sys.sprx.

If I ever get access to the file then I will update the libkernel offsets in the repository.
