### ISSUE TITLE
Will not compile

### ISSUE THREAD

**Issue by godreborn** [McCaulay/mast1c0re#7]
![image](https://github.com/McCaulay/mast1c0re/assets/13548481/122dd85d-453d-4030-9cd4-03995c5a97af)

this is what happens.  I don't understand what's wrong as everything looks correct, and I can build ps2 projects to begin with.

**Comment by McCaulay** [comment]
So it can't find `mips64r5900el-ps2-elf-g++` in your path. Either you have recently modified your .bashrc file and it has not been refreshed in your current terminal session (using `source ~/.bashrc`), or it is related to you running the command with `sudo` which might be using the `/root/.bashrc` instead of your regular user `.bashrc`?

Try to compile without the use of sudo, or make sure you have the `PS2SDK`, `PS2DEV` and `PATH` set correctly in your root `.bashrc` file.

**Comment by godreborn** [comment]
> So it can't find `mips64r5900el-ps2-elf-g++` in your path. Either you have recently modified your .bashrc file and it has not been refreshed in your current terminal session (using `source ~/.bashrc`), or it is related to you running the command with `sudo` which might be using the `/root/.bashrc` instead of your regular user `.bashrc`?
> 
> Try to compile without the use of sudo, or make sure you have the `PS2SDK`, `PS2DEV` and `PATH` set correctly in your root `.bashrc` file.

thanks.  I made it past that, but the samples do this.  the okrager folders are empty btw:

okrager bin/clean/VMC0.card bin/PS5/0_00/okrager/VMC0.card bin/ps-lightbar-PS5-0-00-okrager.elf
make: okrager: Command not found
make: *** [Makefile:51: save] Error 127

**Comment by McCaulay** [comment]
So do you have Okrager installed? (https://github.com/McCaulay/okrager)

If so, it looks like the "okrager" script is not in your PATH. If you installed it with `python -m pip install okrager` it should be in your local `$HOME/.local/bin` directory so you can add the following to your PATH:

`export PATH="$HOME/.local/bin:$PATH"`

If you installed it somewhere else, just add the path to the "okrager" script to your path. If you are not sure where it is installed, you can run `sudo find / -name okrager 2>/dev/null` to search your system for the script.

**Comment by godreborn** [comment]
thanks!  I think we have success:

![image](https://github.com/McCaulay/mast1c0re/assets/13548481/9e5f28e1-3f52-48d1-921e-3b75011b5e05)

**Comment by McCaulay** [comment]
Looks good to me!
